### ISSUE TITLE
bytes object has no attribute hex

### ISSUE THREAD

**Issue by bdambrosio** [turfptax/ugit#8]
Running with micropython 1.19.1 stable.
Do I need a different release?
(xiao esp32-C3)
I'll try latest.

**Comment by turfptax** [comment]
> 

I have a C3 testing now, will see if i can replicate the error.

**Comment by turfptax** [comment]
I tried to replicate this with a ESP32 C3 mini by wemos v1.0.0 

Using micropython firmware: firmware-LOLIN_C3_MINI-v1.19.1-669-gd4b9df176.bin

I did not receive that error. It worked although i had to set ```python wlan.config(txpower=8.5)``` in order to connect because of the ESP32 C3 mini v1.0.0 Error with the antenna. But it pulled all files after ugit.pull_all()

Please let me know if the latest version makes a difference.

**Comment by bdambrosio** [comment]
import binascii
    #return(hash.hex())
    return binascii.hexlify(hash).decode()

seems to fix it (2 spots)

**Comment by bdambrosio** [comment]
Ah, ok. I was (am) running with esp32c3-usb-20220618-v1.19.1.bin
tnx!

**Comment by bdambrosio** [comment]
btw, XIAO esp32C3 has an external 'stick-on' flat antenna, very solid wifi.

**Comment by bdambrosio** [comment]
Yup, esp32c3-usb-20221220-unstable-v1.19.1-782 fixes it.
tnx

**Comment by turfptax** [comment]
> import binascii #return(hash.hex()) return binascii.hexlify(hash).decode()
> 
> seems to fix it (2 spots)

That is awesome that you found a fix.

The hex value of the hash is truly only for readability. It might be wise to remove the hex value and deal only with the byte object instead.

Since we are not able to replicate the SHA1 that GitHub api provides the SHA1 internal has is only meant to check if we have an update. That feature is not yet in ugit. 

I believe the best long-term fix will be not converting to hex .

**Comment by turfptax** [comment]
Ah even better! Latest release fixes it is good.
